<div class="tasks-view-page">
    <form method="POST" action="<?php echo $this->url('task', array('action' => 'save')); ?>">
        <div class="row mb-4">
            <div class="col-md-6">
                <h3 class="float-left">Manage Tasks</h3>
                <a class="float-left ml-3 mnt-3" href="<?php echo $this->url('task'); ?>" title="View all tasks">
                    <button type="button" class="btn btn-outline-primary float-left">View all</button>
                </a>
            </div>
            <div class="col-md-6 text-right">
                <?php if (!empty($this->object->id)): ?>
                    <a class="nounderline" href="<?php echo $this->url("task/wildcard", array('action' => 'delete', 'id' => $this->object->id)); ?>">
                        <button type="button" class="btn btn-danger">Delete</button>
                    </a>
                <?php endif; ?>
                <button type="submit" class="btn btn-primary ml-2">Save</button>
            </div>
        </div>
        <input id="id" name="id" type="hidden" value="<?php echo $this->object->id; ?>" />
        <div class="row mb-3">
            <div class="col-6">
                <label for="name">Name</label>
                <input type="text" name="name" class="form-control" id="name" placeholder="Name" value="<?php echo $this->object->name; ?>" required />
            </div>
            <div class="col-3">
                <label for="status">Status</label>
                <select name="status" id="status" class="form-control">
                    <option value="<?php echo \Mailman\Entity\Task::STATUS_SCHEDULED; ?>">Scheduled</option>
                    <option value="<?php echo \Mailman\Entity\Task::STATUS_PROCESSING; ?>" <?php if ($this->object->status === \Mailman\Entity\Task::STATUS_PROCESSING) { echo 'selected'; } ?>>Processing</option>
                    <option value="<?php echo \Mailman\Entity\Task::STATUS_FINISHED; ?>" <?php if ($this->object->status === \Mailman\Entity\Task::STATUS_FINISHED) { echo 'selected'; } ?>>Finished</option>
                    <option value="<?php echo \Mailman\Entity\Task::STATUS_IDLE; ?>" <?php if ($this->object->status === \Mailman\Entity\Task::STATUS_IDLE) { echo 'selected'; } ?>>Idle</option>
                </select>
            </div>
            <div class="col-3">
                <label for="type">Type</label>
                <select name="type" id="type" class="form-control" disabled>
                    <option value="<?php echo \Mailman\Entity\Task::TYPE_MAILER; ?>">Mail Scheduler</option>
                    <option value="<?php echo \Mailman\Entity\Task::TYPE_IMPORT; ?>" <?php if ($this->object->type === \Mailman\Entity\Task::TYPE_IMPORT) { echo 'selected'; } ?>>Contacts Import</option>
                </select>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-6">
                <label for="scheduled-at">Scheduled At</label>
                <div class="form-group">
                    <div class="input-group date" id="scheduled-at">
                        <input type="text" name="scheduledAt" class="form-control" value="<?php if (!empty($this->object->scheduledAt)) { echo $this->object->scheduledAt->format('Y-m-d H:i:s'); } ?>" required />
                        <span class="input-group-addon">
                            <span class="fa fa-calendar"></span>
                        </span>
                    </div>
                </div>
            </div>
            <?php if ($this->object->createdAt): ?>
                <div class="col-6">
                    <label for="created-at">Created At</label>
                    <div class="form-group">
                        <div class="input-group date" id="created-at">
                            <input type="text" class="form-control" value="<?php echo $this->object->createdAt->format('Y-m-d H:i:s'); ?>" readonly />
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <?php if (!empty($this->stats)): ?>
            <div class="row mb-4 text-center">
                <?php $columns = 12 / count($this->stats); ?>
                <?php foreach ($this->stats as $key => $value): ?>
                    <div class="col-<?php echo $columns; ?>">
                        <div class="px-5 card">
                            <div class="card-block">
                                <h2><?php echo $value; ?></h2>
                                <span><small><?php echo ucfirst($key); ?></small></span>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
        <?php if ($this->object->id): ?>
            <div class="row mb-5">
                <div class="col-12">
                    <label for="encodedData">Data</label>
                    <textarea name="encodedData" class="form-control" id="encodedData" rows="7" readonly><?php echo $this->object->encodedData; ?></textarea>
                </div>
            </div>
        <?php else: ?>
            <div class="row mb-5">
                <input id="encodedData" name="encodedData" type="hidden" />
                <div class="col-6">
                    <label for="email-template">Email Template</label>
                    <select id="email-template" class="form-control" required>
                        <option value="">--- Select ---</option>
                        <?php foreach ($this->emails as $email): ?>
                            <option value="<?php echo $email->id; ?>"><?php echo $email->title; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-6">
                    <label for="contact-list">Mailing List</label>
                    <select id="contact-list" class="form-control" required>
                        <option value="">--- Select ---</option>
                        <?php foreach ($this->lists as $list): ?>
                            <option value="<?php echo $list->id; ?>"><?php echo $list->name; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        <?php endif; ?>
    </form>
</div>
<script type="text/javascript">
    $(function() {
        $('#scheduled-at').datetimepicker({format: 'YYYY-MM-DD HH:mm:ss'});
        
        $('form').on('submit', function(e) {
            e.preventDefault();
            
            if (!$('#id').val()) {
                var data = {
                    template: $('#email-template').val(),
                    list: $('#contact-list').val()
                };

                $('#encodedData').val(JSON.stringify(data));
            }
            
            $('#type').attr('disabled', false);$(this).off('submit').submit();
        });
    });
</script>